AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyFlaskApi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 128
      Timeout: 15
      Layers:
        - !Ref ReqsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          FLASK_ENV: development
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: ANY

  ReqsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: reqs
      ContentUri: reqs/
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain
